public enum CaravanEventType {
    ON_GAME_STARTED,
    ON_GAME_PAUSED,
    ON_GAME_UNPAUSED,
    ON_NEW_GAME,
    ON_ENCOUNTER_STARTED,
    ON_CARAVAN_STOPPED,
    ON_ENCOUNTER_ENDED,
    ADD_CARAVAN,
    ADD_HUMAN,
    DESTROY_CARAVAN,
    DESTROY_HUMAN,
    NEXT_ACTION,
    DO_GAME_OVER,
    SET_AREA,
    SET_QUEST
}

public enum CameraEventType {
    DO_SCREENSHAKE,
    SET_INTERACTABLE,
}